name: herald_flutter
description: A flutter project to test Herald running in the background.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  nanoid: ^1.0.0
  shared_preferences: ^2.0.16
  cupertino_icons: ^1.0.5
  intl: ^0.18.0
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true